### ISSUE TITLE
Setting up   ~/.kube/config should be separated from helmsman

### ISSUE THREAD

**Issue by KamranAzeem** [Praqma/helmsman#44] opened 2018-06-20 06:48 UTC
had great trouble (last night) getting a simple/example mysql deploy to work because  `~/.kube/config` was setup on my local machine using `gcloud --jason` method, and I could not replicate that setup using helmsman and circleci. Currently helmsman uses a combination of certificates and usernames and password passed to it through circleci env variable, which does not allow it to work with my use-case.
In short, I see that there are many ways to configure  `~/.kube/config` , and not  all use the regular options of certificates and usernames and passwords. e.g. helmsman is built on alpine image, which does not contain gcloud commands. So even if I can magically copy the exact .kube/config from my  computer into the helmsman container, it still fails as gcloud command is hard-coded in the .kube/config file when this file is created using `gcloud auth --json=file` method.

![screenshot from 2018-06-20 00-54-01](https://user-images.githubusercontent.com/4216369/41641827-d45cfdde-7466-11e8-8942-b89ae7f3be36.png)

I suggest that we move the ~/.kube/config setup part out of helmsman completely and let something else take care of it. Helmsman should expect it to work before it starts to deploy helm charts on the cluster.

**Comment by krogon** [comment] 2018-06-20 17:04
If your config contains `settings.kubeContext` pointing to existing context it uses it without reconfiguration and you've got what you want: separation of setting up .kube/config out of helmsman.

Regarding your issue, seems like your .kube/config invokes gcloud as external binary, which is not present in standard helmsman docker image. If the binary is not a big overhead in overall docker size feel free to prepare PR to existing Dockerfile. Otherwise prepare your own image basing on helmsman official.

**Comment by KamranAzeem** [comment] 2018-06-20 19:30
Thanks for the tip.

I tried to run a container with alpine image , and installed gcloud in it. Good. I then tried to bring in my gcloud auth json file (as base64) to the container using env variable. I noticed that in Alpine, it is only able to store about 1011 bytes /characters in the env variable. So when I decode this file and try to create it as json file on the disk in the container, the file is not completely restored.  So even if I have gcloud in the helmsman container, I cannot get a large json file as env variable. 

Screenshots attached:
![screenshot from 2018-06-20 21-13-16](https://user-images.githubusercontent.com/4216369/41680158-e3dc4d54-74d0-11e8-8e62-aa5fbeefb8c7.png)

![screenshot from 2018-06-20 21-13-47](https://user-images.githubusercontent.com/4216369/41680164-e797b258-74d0-11e8-89cf-53b90e0c2552.png)


![screenshot from 2018-06-20 21-14-09](https://user-images.githubusercontent.com/4216369/41680166-eb293c0c-74d0-11e8-814a-c8b4c352c984.png)


I tried to do the same on a fedora:27 container, and it works properly, both in bash and sh. So probably alpine has some limitation?

I will probably create a separate Docker image based on Fedora and use that for now.

**Comment by sami-alajrami** [comment] 2018-06-25 09:57
thanks @KamranAzeem  .. this is an intended behaviour and not a bug. Helmsman needs to be generic to support all clusters regardless of their provider. The generic way is to use credentials and certificates to setup the connection to the cluster. Once you provide these details to Helmsman, you don't need to do anything with the `~/.kube/config`. [Google Cloud API](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.zones.clusters/get) seems to support getting the certificates, although the web console seems not to support extracting all of the certs. Terraform also supports extracting all certs for a GKE cluster https://www.terraform.io/docs/providers/google/r/container_cluster.html#attributes-reference 

I don't see the need to change the way Helmsman connects to the clusters. However, as @krogon suggested you could customize the docker image with any tools you need. Once you establish cluster connection out of Helmsman, you can use the context name in your DSF (toml/yaml file) and skip all the certs and credentials:

```
[settings]
kubeContext = "your-already-configured-context-name"
```
Helmsman will use this context then and everything should work from there. I will close this issue for now, but feel free to reopen it if you still experiencing problems.

**Closed by sami-alajrami** 2018-06-25 09:57 UTC
