### ISSUE TITLE
helmsman always adds tests

### ISSUE THREAD

**Issue by regner** [Praqma/helmsman#179] opened 2019-01-22 19:01 UTC
I don't know if this is a Helmsman issue or an issue with Helm or an issue with the chart.

Helmsman version 1.7.2.

When I run `helmsman -f helmsman.yaml` it always wants to deploy the test pods for the [mattermost-team-edition](https://github.com/helm/charts/tree/master/stable/mattermost-team-edition) chart.

Here is the diff:

```bash
staging, mattermost-mattermost-team-edition-test-hqznc, Pod (v1) has been removed:
- # Source: mattermost-team-edition/templates/tests/mattermost-test.yaml
- apiVersion: v1
- kind: Pod
- metadata:
-   name: "mattermost-mattermost-team-edition-test-hqznc"
-   labels:
-     app.kubernetes.io/name: mattermost-team-edition
-     app.kubernetes.io/instance: mattermost
-     app.kubernetes.io/managed-by: Tiller
-     helm.sh/chart: mattermost-team-edition-2.1.3-6
-   annotations:
-     "helm.sh/hook": test-success
- spec:
-   initContainers:
-   - name: "test-framework"
-     image: "dduportal/bats:0.4.0"
-     command:
-     - "bash"
-     - "-c"
-     - |
-       set -ex
-       # copy bats to tools dir
-       cp -R /usr/local/libexec/ /tools/bats/
-     volumeMounts:
-     - mountPath: /tools
-       name: tools
-   containers:
-   - name: mattermost-test
-     image: "mattermost/mattermost-team-edition:4.10.3"
-     command: ["/tools/bats/bats", "-t", "/tests/run.sh"]
-     volumeMounts:
-     - mountPath: /tests
-       name: tests
-       readOnly: true
-     - mountPath: /tools
-       name: tools
-   volumes:
-   - name: tests
-     configMap:
-       name: mattermost-mattermost-team-edition-tests
-   - name: tools
-     emptyDir: {}
-   restartPolicy: Never
+
staging, mattermost-mattermost-team-edition-test-nr68t, Pod (v1) has been added:
-
+ # Source: mattermost-team-edition/templates/tests/mattermost-test.yaml
+ apiVersion: v1
+ kind: Pod
+ metadata:
+   name: "mattermost-mattermost-team-edition-test-nr68t"
+   labels:
+     app.kubernetes.io/name: mattermost-team-edition
+     app.kubernetes.io/instance: mattermost
+     app.kubernetes.io/managed-by: Tiller
+     helm.sh/chart: mattermost-team-edition-2.1.3-6
+   annotations:
+     "helm.sh/hook": test-success
+ spec:
+   initContainers:
+   - name: "test-framework"
+     image: "dduportal/bats:0.4.0"
+     command:
+     - "bash"
+     - "-c"
+     - |
+       set -ex
+       # copy bats to tools dir
+       cp -R /usr/local/libexec/ /tools/bats/
+     volumeMounts:
+     - mountPath: /tools
+       name: tools
+   containers:
+   - name: mattermost-test
+     image: "mattermost/mattermost-team-edition:4.10.3"
+     command: ["/tools/bats/bats", "-t", "/tests/run.sh"]
+     volumeMounts:
+     - mountPath: /tests
+       name: tests
+       readOnly: true
+     - mountPath: /tools
+       name: tools
+   volumes:
+   - name: tests
+     configMap:
+       name: mattermost-mattermost-team-edition-tests
+   - name: tools
+     emptyDir: {}
+   restartPolicy: Never
```

It isn't the end of the world as it just recreates the test pods. If it was recreating running pods it would be really painful.

Any suggestions on how this can be avoided or fixed? Do I need to raise it with the Helm chart maintainer?

**Comment by sami-alajrami** [comment] 2019-01-24 09:53
great! 🎉 we will add the flag once it's released in diff

**Comment by regner** [comment] 2019-01-31 21:44
After discussing it some more in https://github.com/databus23/helm-diff/issues/114 the point was made that disabling all hooks is maybe a bad idea. I don't know what the preference for Helmsman is, disable diffing for all hooks or just test hooks.

I opened another PR into helm-diff to add the option to disable just test hooks if that is what Helmsman would prefer: https://github.com/databus23/helm-diff/pull/119

**Comment by sami-alajrami** [comment] 2019-02-13 10:24
thanks @regner I can see why it can sound problematic (e.g. for hooks at post-upgrade, post-install ... ) .. but these hooks should not be the cause for triggering an upgrade (or any other operation) in helmsman. 

From helmsman point of view, having all hooks disabled in the diff command (with some optional flag) will allow helmsman to make a correct decision about the needed operation if any.
I don't see the case where a diff caused by a hook would be needed for deciding to upgrade a release! 

When helmsman triggers an upgrade , for instance, any post-upgrade hooks will still be executed! (unless you pass `no-hooks` as an additional helm command)

**Comment by regner** [comment] 2019-02-13 16:47
If thats the case, then I guess it is just waiting for helm-diff to cut a new release.

**Comment by regner** [comment] 2019-05-15 03:29
helm-diff just cut a new release with my fix in it: https://github.com/databus23/helm-diff/releases

**Closed** 2019-06-21 11:20 UTC
