### ISSUE TITLE
helmsman --dry-run && --apply recreate the resource on every run

### ISSUE THREAD

**Issue by NandoTheessen** [Praqma/helmsman#267] opened 2019-07-12 10:32 UTC
Hi!
I've got an issue that I know should be fixed already but isn't. 
I'm working with the anchore-engine which I've deployed into our K8s cluster and where whenever it is already deployed helmsman wants to re-create the release because the chart has changed (which is has not).
This is the output of `--show-diff` right after I deployed the application:
```± % helmsman -f helmsman-testing-stuff.toml --show-diff                                                                                                       !4543
 _          _ 
| |        | | 
| |__   ___| |_ __ ___  ___ _ __ ___   __ _ _ __
| '_ \ / _ \ | '_ ` _ \/ __| '_ ` _ \ / _` | '_ \ 
| | | |  __/ | | | | | \__ \ | | | | | (_| | | | | 
|_| |_|\___|_|_| |_| |_|___/_| |_| |_|\__,_|_| |_| version: v1.9.1
A Helm-Charts-as-Code tool.


2019/07/12 12:29:44 INFO: substituting env variables in values and secrets files ...
2019/07/12 12:29:44 INFO: Parsed TOML [[ helmsman-testing-stuff.toml ]] successfully and found [ 1 ] apps.
2019/07/12 12:29:44 INFO: namespace validation -- Tiller is NOT desired to be deployed in namespace [ kube-system ].
2019/07/12 12:29:44 INFO: namespace validation -- Either no or invalid certs/keys provided for DEPLOYING Tiller with TLS in namespace [ testing-stuff ].
2019/07/12 12:29:48 INFO: checking what I need to do for your charts ... 
2019/07/12 12:29:48 INFO: mapping the current helm state ...
2019/07/12 12:29:49 INFO: checking if any Helmsman managed releases are no longer tracked by your desired state ...
2019/07/12 12:29:51 INFO: no untracked releases found.
2019/07/12 12:29:51 INFO: sorting the commands in the plan based on priorities (order flags) ... 
2019/07/12 12:29:51 ----------------------
2019/07/12 12:29:51 INFO: Plan generated at: Fri Jul 12 2019 10:29:48
2019/07/12 12:29:51 DECISION: release [ anchore ] is desired to use a new Chart [ /home/nando/repos/devops/helm/charts/anchore ]. I am planning a purge delete of the current release and will install it with the new chart in namespace [[ testing-stuff ]] -- priority: 0
2019/07/12 12:29:51 INFO: completed successfully!
2019/07/12 12:29:51 INFO: cleaning up sensitive and temp files```

`--dry-run` Also recreates the release.
If I'm doing something wrong please let me know, then I'll close the issue.
We're running on AWS EKS 1.13 (k8s 1.13.7)

**Comment by sami-alajrami** [comment] 2019-07-15 11:31
Hi @NandoTheessen this is caused by this if statement https://github.com/Praqma/helmsman/blob/ebbb84280d45c3296238711a41006a813d7bcc08/decision_maker.go#L220 

The first check `extractChartName(r.Chart)` results in `anchor` as you can verify [here](https://play.golang.org/p/6qFrP9LI0p9). The second part extracts the chart name from the helm state which you can check by running `helm ls`. If you see another name than `anchor-x.y.z` under the `CHART` column, this would be the reason why helmsman considers the chart changing .. the chart directory name must match the chart name in Charts.yaml within your chart.

If this is not the case, then please share here the result of your `helm ls` and the results of running `helmsman with the verbose flag` and the part of your DSF where anchore is defined.

**Comment by sami-alajrami** [comment] 2019-07-26 10:13
@NandoTheessen should we close this issue? assuming that my answer above fixed your problem?

**Closed** 2020-09-18 06:35 UTC
