### ISSUE TITLE
Variable substitution not working in env files

### ISSUE THREAD

**Issue by gyszalai** [Praqma/helmsman#656] opened 2022-05-12 14:40 UTC
It seems that environment variables are not substituted in env files.
I use helmsman 3.9.0. I checked the `godotenv` library that this project uses for loading env files and from version 1.3.0 it should work. Helmsman 3.9.0 uses 1.4.0 of this lib.

Example:

**helmsman.yaml**
```yaml
context: mycontext
metadata:
  test: "${TEST_VAR}"
```

**.env file**
```env
TEST_VAR=${SOMETHING}
```

**Calling helmsman:**
```
export SOMETHING=some_value
helmsman --debug -e .env -f helmsman.yaml
```

**result (from helmsman output)**
```
Metadata: 
--------- 
test :  

Context: 
--------- 
mycontext
```

Am I doing somethong wrong or is it a bug?

**Comment by luisdavim** [comment] 2022-05-13 10:05
Hi, you need to enable it with the config flags `--subst-env-values`

**Comment by gyszalai** [comment] 2022-05-13 10:55
Hi, thanks for your suggestion, but the situation is the same with `--subst-env-values`

Actually, according to the documentation, this CLI option is for value files not env files:
`--subst-env-values` turn on environment substitution in values files.

I need the substitution in an env file that is passed to helmsman with the `-e` option.

**Comment by gyszalai** [comment] 2022-05-13 10:58
Our use case is that the operations team provides a helm repo base URL in an env var on the CI server and we would like to use it in our `.env` file like this:

```
HELM_REPO_URL=${HELM_REPO_BASE_URL}/our-repo/
```

**Comment by luisdavim** [comment] 2022-05-13 23:35
Oh, I think the problem might be that we're not expanding the environment variables inside the env file. I'll look into that.

**Comment by luisdavim** [comment] 2022-05-14 15:17
Hi, I've opened a PR to address this (#657) would you be able to test your use case using a build from that branch?

**Comment by luisdavim** [comment] 2022-05-14 22:59
I was checking `godotenv`'s code and my PR might  not be enough, `godotenv` only expands variables that are set in the loaded env files.

There are issues regarding this:
* https://github.com/joho/godotenv/issues/102
* https://github.com/joho/godotenv/issues/74

**Comment by luisdavim** [comment] 2022-05-14 23:24
as a workaround, untill this gets fixed upstream, you can try adding something like this in your CI:

```sh
export SOMETHING=some_value
printenv > cur.env
helmsman --debug  -e cur.env -e .env -f helmsman.yaml
```

**Comment by luisdavim** [comment] 2022-05-17 07:40
Keeping this open as `godotenv`'s implementation might still affect the issue

**Comment by gyszalai** [comment] 2022-05-17 08:13
Sorry, I was offline for a few days. I'll check if it solves our problem.

**Comment by gyszalai** [comment] 2022-05-17 08:46
just built helmsman from the master branch, but it doesn't seem to be working :(

**Comment by luisdavim** [comment] 2022-05-17 09:25
Yeah, I think the problem is that with the current implementation `godotenv` will expand `HELM_REPO_URL=${HELM_REPO_BASE_URL}/our-repo/` as `HELM_REPO_URL=/our-repo/` unless `HELM_REPO_BASE_URL` is also defined in the env file, there are a bunch o issues and PRs open about this in https://github.com/joho/godotenv, but the maintainer isn't responding....

There's also https://github.com/subosito/gotenv I can have a look at that and see it would be a suitable replacement if the issue doesn't get fixed in `godotenv`...

**Comment by gyszalai** [comment] 2022-05-17 10:22
Yes, I just checked the `godotenv` project and saw that there are multiple issues regarding this problem. Anyway, thank you for your efforts! That would be great if you could look at the other lib (gotenv), though.

**Comment by luisdavim** [comment] 2022-05-20 10:28
Once https://github.com/subosito/gotenv/pull/15 is merged, I think we can switch from `godotenv` to `gotenv`.

**Comment by luisdavim** [comment] 2022-05-23 19:12
Hi @gyszalai would you be able to test a build from #665 and let me know if it solves your use case?

**Comment by gyszalai** [comment] 2022-05-24 05:54
Hi @luisdavim I just checked it and it looks good! 👍 The variable is resolved either if its in another env file or just simply exported before calling helmsman. Thank you for your efforts!

**Closed** 2022-05-24 12:58 UTC
